FROM python:3.7.1

RUN mkdir /app
WORKDIR /app

RUN apt update -y 
RUN apt install -y python-pip python-dev

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

ADD . /app

EXPOSE 5000

CMD flask run --host=0.0.0.0
